# Use the official MySQL image as the base image
FROM mysql:latest

# Set environment variables for MySQL configuration
ENV MYSQL_DATABASE Cloud
ENV MYSQL_USER php_docker
ENV MYSQL_PASSWORD password
ENV MYSQL_ALLOW_EMPTY_PASSWORD 1

# Copy the SQL script to initialize the database into the container
COPY ./db/database.sql /docker-entrypoint-initdb.d/database.sql
